// Generated by app/tools/build_bundle.py (stamp_shell): the app shell the service worker saves as one
// version, and its fingerprint. A new version here makes installed copies offer "Refresh".
// After ANY change to the app's files run: python app/tools/build_bundle.py --stamp
self.DAMDAYS_SHELL = {
 "version": "70a65ae1d7",
 "files": [
  "./",
  "index.html",
  "manifest.webmanifest",
  "data/datasets.js",
  "data/real/parts.js",
  "css/base.css",
  "css/dam.css",
  "css/farm.css",
  "css/legacy.css",
  "css/more.css",
  "css/proof.css",
  "css/pwa.css",
  "css/shell.css",
  "css/tokens.css",
  "css/welcome.css",
  "js/charts.js",
  "js/colors.js",
  "js/dam-card.js",
  "js/dam-sheet.js",
  "js/data.js",
  "js/format.js",
  "js/main.js",
  "js/map.js",
  "js/pwa.js",
  "js/settings.js",
  "js/sheet.js",
  "js/sketch.js",
  "js/text.js",
  "js/views/about.js",
  "js/views/farm.js",
  "js/views/more.js",
  "js/views/proof.js",
  "js/views/questions.js",
  "js/views/rating.js",
  "js/views/region.js",
  "js/views/replay.js",
  "js/views/rewind.js",
  "js/views/runway.js",
  "js/views/welcome.js",
  "fonts/atkinson-hyperlegible-next-latin.woff2",
  "fonts/fonts.css",
  "icons/icon.svg",
  "icons/favicon-32.png"
 ],
 "parts": [
  "data/real/parts.js"
 ]
};
