"""Pack one dataset folder's JSON files into a single bundle.js that the app loads.

Why this exists: when you double-click index.html, the browser opens it from
disk (a file:// address) and blocks JavaScript from reading other local files
with fetch(). It does allow <script src="...">. So we wrap the JSON files in
one small script that sets a global variable. The JSON files stay the
"source of truth" described in app/DATA_CONTRACT.md; bundle.js is a copy.

If the folder also has farms.json (the demo farms and their weekly texts, written
by scripts/16_weekly_texts.py), it is packed too, for the app's "My farm" view.
It is optional: a dataset without it still works, and My farm then starts empty.
The same goes for proof.json (the Proof view's charts, written by
scripts/17_proof_data.py): without it, the Proof view says the charts need it.
And for track_record.json (each dam's 2016-2026 track record, written by
scripts/18_track_record.py): without it, the dam cards and My farm leave it out.

This script also rewrites app/data/datasets.js, the list of datasets the app
can use. "real" is always listed first, so the app prefers real data whenever
a real bundle exists.

Usage (from the repo root):
    python app/tools/build_bundle.py app/data/mock
    python app/tools/build_bundle.py app/data/real
"""
import json
import sys
from pathlib import Path

# The six files every dataset folder must contain (see DATA_CONTRACT.md).
PARTS = ["meta", "forecasts", "curves", "history", "cells", "scoreboard"]

# Files packed only if the folder has them.
OPTIONAL_PARTS = ["farms", "proof", "track_record"]

# The top-level keys each file must have. A light check that catches a
# half-written export before it reaches the app.
REQUIRED_KEYS = {
    "meta": ["schema_version", "is_mock", "region", "horizon_days"],
    "forecasts": ["dams", "issues"],
    "curves": ["horizons_days", "issues"],
    "history": ["first_month", "last_month", "by_dam"],
    "cells": ["cells", "seasons"],
    "scoreboard": ["source", "rating"],
    "farms": ["date", "farms"],
    "proof": ["schema_version", "test", "unseen_exam", "calibration", "by_year", "dam_by_dam"],
    "track_record": ["schema_version", "label", "min_judged", "tip", "dams", "farms"],
}

# Datasets the app knows about, in order of preference.
PREFERENCE = ["real", "mock"]


def read_part(folder, name):
    """Read one JSON file from the dataset folder and check its top-level keys."""
    path = folder / f"{name}.json"
    if not path.exists():
        raise SystemExit(f"Missing {path}. Every dataset needs {', '.join(PARTS)}.")
    with open(path, encoding="utf-8") as f:
        content = json.load(f)
    missing = [key for key in REQUIRED_KEYS[name] if key not in content]
    if missing:
        raise SystemExit(f"{path} is missing the key(s): {', '.join(missing)}")
    return content


def write_bundle(folder):
    """Combine the six JSON files (and farms.json, proof.json and track_record.json, if there) into folder/bundle.js."""
    bundle = {name: read_part(folder, name) for name in PARTS}
    for name in OPTIONAL_PARTS:
        if (folder / f"{name}.json").exists():
            bundle[name] = read_part(folder, name)
            print(f"Packed the optional {name}.json too")
    # Compact separators keep the file small; the JSON files stay readable.
    text = json.dumps(bundle, separators=(",", ":"), ensure_ascii=False)
    header = (
        "// Generated by app/tools/build_bundle.py from the JSON files in this folder.\n"
        "// Do not edit by hand: edit or re-export the JSON, then rebuild.\n"
    )
    out_path = folder / "bundle.js"
    out_path.write_text(header + "window.DAMDAYS_BUNDLE = " + text + ";\n", encoding="utf-8")
    size_kb = out_path.stat().st_size / 1024
    print(f"Wrote {out_path} ({size_kb:.0f} KB)")


def write_dataset_list(data_dir):
    """List every dataset folder that has a bundle.js, preferred first, in datasets.js."""
    found = [name for name in PREFERENCE if (data_dir / name / "bundle.js").exists()]
    out_path = data_dir / "datasets.js"
    out_path.write_text(
        "// Generated by app/tools/build_bundle.py. The app loads the first dataset listed.\n"
        "window.DAMDAYS_DATASETS = " + json.dumps(found) + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {out_path}: {found}")


def main():
    if len(sys.argv) != 2:
        raise SystemExit("Usage: python app/tools/build_bundle.py <dataset folder>")
    folder = Path(sys.argv[1]).resolve()
    write_bundle(folder)
    write_dataset_list(folder.parent)


if __name__ == "__main__":
    main()
